name: CI

on:
  pull_request:
    branches: [main]

jobs:
  validate_pressed:
    name: Validate preseed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure environment
        run: |
          sudo apt-get update
          sudo apt-get install debconf-utils
      - name: Validate preseed
        run: debconf-set-selections -v -c iso_tools/preseed.seed.base

  build_iso_vm:
    name: Build ISO (VM)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Test ISO (VM)
        run: ./build.sh -v -f

  build_iso_blade:
    name: Build ISO (Blade)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Test ISO (Blade)
        run: ./build.sh -f
